<div style="display:flex; justify-content:center; align-items:center; margin:25px 0;">
    
![jupyter](img/logo.png)

</div>

<div align="center">

# **Normalización**

</div>


<div style="display:flex; justify-content:center; align-items:center; margin:25px 0;">
    
![jupyter](img/python.png)

</div>

<div align="center">
    
## **Nombre**: ***Adriel Bedoya***

</div>


### ¿Qué es Estandarización?

Es un proceso en el que los valores de una variable se transforman para que tengan una media igual a 0 y una desviación estándar igual a 1. Esto se logra restando la media a cada dato y dividiendo el resultado para la desviación estándar. A diferencia de otros métodos, aquí no se ajustan los datos a un rango específico, sino que se reescalan en función de su distribución, lo que permite entender qué tan lejos está cada valor respecto al promedio

### ¿Para que sirve?

Sirve para preparar los datos antes de aplicar algoritmos que asumen una distribución normal o que son sensibles a la escala de los datos, como regresión lineal, máquinas de soporte vectorial o redes neuronales. Al centrar los datos alrededor de cero y normalizar su variabilidad, se mejora la estabilidad numérica de los modelos, se facilita el aprendizaje y se evita que variables con valores grandes dominen sobre otras. También permite comparar variables en términos de desviaciones respecto a la media, lo cual es útil en análisis estadístico

### ¿En qué se diferencia la Normalización y la Estandarización?

La principal diferencia entre estandarización y normalización está en cómo transforman los datos. La normalización lleva los valores a un rango fijo (0 y 1), mientras que la estandarización los ajusta según su media y desviación estándar, sin limitar el rango final. Además, la normalización es más sensible a valores extremos (outliers), ya que depende de los valores mínimo y máximo, mientras que la estandarización es más robusta frente a estos casos.

In [8]:
from sklearn import preprocessing
import numpy as np

In [9]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [14]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [15]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [16]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)
# ???

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [17]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_std, X_train_2_std))

True


# Github
<div style="margin-left: 330px">
    
![](img/github.png)
</div>

## Para entrar, de click [aquí](https://github.com/AlejandroJonnath/MachineLearning2.git)