<div style="display:flex; justify-content:center; align-items:center; margin:25px 0;">
    
![jupyter](img/logo.png)

</div>

<div align="center">

# **Normalización**

</div>


<div style="display:flex; justify-content:center; align-items:center; margin:25px 0;">
    
![jupyter](img/python.png)

</div>

<div align="center">
    
## **Nombre**: ***Adriel Bedoya***

</div>

Es un proceso mediante el cual se transforman los valores de un conjunto de datos para que todos estén en una misma escala o rango. Esto significa que, si tienes variables con diferentes magnitudes (por ejemplo, edad en años y salario en miles), la normalización ajusta esos valores para que sean comparables entre sí, generalmente llevándolos a un rango común como 
[
0
,
1
]
[0,1]. No cambia la información esencial de los datos, sino la forma en que están representados, facilitando su uso en análisis posteriores.

Sirve principalmente para mejorar el rendimiento de los algoritmos de análisis de datos y aprendizaje automático. Muchos modelos, especialmente los que dependen de distancias (como KNN o clustering), pueden verse afectados si una variable tiene valores mucho más grandes que otra, ya que dominaría el cálculo. Al normalizar, se evita este problema y se logra que todas las variables tengan el mismo peso en el análisis. Además, ayuda a que los modelos converjan más rápido y a obtener resultados más precisos y estables

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [4]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [6]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])

# Normalizar los datos de "X_test"
# ???

In [8]:
#Como son un mismo conjunto de datos, solo tenemos que aplicar con f

#Ya está arriba pero f es f = normalizer.fit(X_train) (ya normalizamos antes)
X_test_norm = f.transform(X_test)
#imprimimos el valor
print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


# Github
<div style="margin-left: 330px">
    
![](img/github.png)
</div>

## Para entrar, de click [aquí](https://github.com/AlejandroJonnath/MachineLearning2.git)